// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

package com.hzx.grpc.oss;

public final class OssProto {
  private OssProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_objectStorageService_ReqData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_objectStorageService_ReqData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_objectStorageService_RepData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_objectStorageService_RepData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\toss.proto\022\024objectStorageService\"\027\n\007Req" +
      "Data\022\014\n\004data\030\001 \001(\t\"\027\n\007RepData\022\014\n\004data\030\001 " +
      "\001(\t2\205\002\n\024ObjectStorageService\022M\n\tGetStrea" +
      "m\022\035.objectStorageService.ReqData\032\035.objec" +
      "tStorageService.RepData\"\0000\001\022M\n\tSetStream" +
      "\022\035.objectStorageService.ReqData\032\035.object" +
      "StorageService.RepData\"\000(\001\022O\n\tAllStream\022" +
      "\035.objectStorageService.ReqData\032\035.objectS" +
      "torageService.RepData\"\000(\0010\001B\036\n\020com.hzx.g" +
      "rpc.ossB\010OssProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_objectStorageService_ReqData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_objectStorageService_ReqData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_objectStorageService_ReqData_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_objectStorageService_RepData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_objectStorageService_RepData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_objectStorageService_RepData_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
