// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

package com.hzx.grpc.oss;

public interface RepDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:objectStorageService.RepData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
