// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloword.proto

package com.hzx.grpc;

public interface HahahaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HahahaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
