// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.hzx.grpc.api;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
